server:
  port: 8080
 
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://1.15.116.70:5432/book
    driver-class-name: org.postgresql.Driver
 
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.book.entity